// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplicationReact.Models;

namespace WebApplicationReact.Migrations
{
    [DbContext(typeof(CarDBContext))]
    [Migration("20200720051219_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplicationReact.Models.tblCarProp", b =>
                {
                    b.Property<int>("IdCar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Modelo")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Patente")
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("Puertas")
                        .HasColumnType("int");

                    b.HasKey("IdCar");

                    b.ToTable("tblCarProps");
                });
#pragma warning restore 612, 618
        }
    }
}
